### ISSUE TITLE
Versioning docs missing

### ISSUE THREAD

**Issue by ianwallen** [geonetwork/doc#138]
The documentation on the versioning is empty.

https://github.com/geonetwork/doc/blob/develop/source/user-guide/workflow/versioning.rst

Based on the older 2.10.x, there was some versioning documentation in the past.

https://github.com/geonetwork/core-geonetwork/blob/2.10.x/docs/eng/users/source/managing_metadata/versioning/index.rst

Is versioning still supported?  If so - does anyone know why that the versioning documentation was not migrated from 2.10.x to 3.x?  It seems like it would be better to have some versioning documentaiton (even if it may be a little outdated) vs having an empty page.

Thank you

**Comment by jodygarnett** [comment]
My understanding is the team migrating docs from 2.10 ran out of time and did not get all the sections.

**Comment by archaeogeek** [comment]
SVN versioning is now deprecated and the docs have been updated to reflect this in https://github.com/geonetwork/doc/commit/7fea1e402a5ccccc6c932c611fc47f3c740f3929
