### ISSUE TITLE
Can't access documentation

### ISSUE THREAD

**Issue by Maaka2890** [geonetwork/doc#17]
Under "New Features" you've linked to localhost when you're trying to redirect to the new Rest API documentation:

http://www.geonetwork-opensource.org/manuals/trunk/eng/users/overview/change-log/version-3.2.0.html

**Comment by archaeogeek** [comment]
I believe this is deliberate, as it is referencing where you access the api on your own system. However, this isn't clear in the documentation so I will update the main api section at https://geonetwork-opensource.org/manuals/3.4.x/en/api/the-geonetwork-api.html to make this clearer.
