### ISSUE TITLE
Adding MCP of ISO 19115 to geonetwork 3.x

### ISSUE THREAD

**Issue by stevenvandervalk** [geonetwork/doc#2]
Hi, this more a question than issue so apologies.  

Is http://www.geonetwork-opensource.org/manuals/trunk/eng/users/administrator-guide/managing-metadata-standards/index.html#adding-a-schema

still currently the preferred way of adding a schema? 

I see the UI has a "Add or Update a standard" input and I'm wondering if that is the same functionality?

I'd like to add https://marinemetadata.org/references/marineprofile19115 to the latest geonetwork builds and try out the improved metadata editing and faceting UI for users contributing marine metadata.

Thanks!

**Comment by archaeogeek** [comment]
Looks like this question/issue has been languishing for a while, so it's probably out of date- is it OK to close or do you still need assistance?

**Comment by stevenvandervalk** [comment]
All good, thanks :)
