### ISSUE TITLE
Missing example event listener

### ISSUE THREAD

**Issue by arbakker** [geonetwork/doc#215]
The documentation suggests that there should be an example of a listener that prints a string every time a metadata gets removed, however the example seems to be missing:

https://github.com/geonetwork/doc/blob/develop/source/tutorials/hookcustomizations/events/index.rst#simple-example

**Comment by juanluisrp** [comment]
The code is there but is not being rendered for some reason. See the raw view of the file https://raw.githubusercontent.com/geonetwork/doc/develop/source/tutorials/hookcustomizations/events/index.rst

**Comment by arbakker** [comment]
Aah I only viewed the rendered rst file in Github, I did not check the raw rst file. 

The java code block does not seem to have the same indendation as the xml code block above, I suspect that might be the issue.
