### ISSUE TITLE
RDF DCAT end point

### ISSUE THREAD

**Issue by nmtoken** [geonetwork/doc#50]
ref: https://geonetwork-opensource.org/manuals/3.6.x/en/api/rdf-dcat.html

Is there an end point?

I know you can get RDF DCAT from a path like: 

{your service}/srv/eng/rdf.metadata.get?uuid={some_uuid}

or 

{your service}/srv/eng/rdf.metadata.get?id={some_id}

but I can't find an end point

**Comment by fxprunayre** [comment]
Maybe use the dcat output schema in CSW ?

**Comment by nmtoken** [comment]
Possibly, but then documentation (latest now https://geonetwork-opensource.org/manuals/3.8.x/fr/api/index.html) seems wrong listing `CSW` and `RDF DCAT end point` as separate items

I guess i'm just dumb, and it's probably

{your server}/{your catalogue}/srv/eng/rdf.metadata.get?

If I do that on a GN 3.8.0.0 instance I get a message like:

`{"error": { "message": "java.lang.Exception: Request must contain a UUID (uuid) or an ID (id)" , "class": "RuntimeException" , "request": {} } }`

Which is promising, I guess I was expecting a way or interrogating the endpoint to discover capabilities, available records etc like a CSW endpoint, but perhaps you can just get a record if you somehow already know it's identifier?

**Comment by archaeogeek** [comment]
rdf.search allows you to get multiple records, and you can filter on (eg category) with rdf.search?_cat=foo. There's already an issue (https://github.com/geonetwork/doc/issues/38) to get some documentation into that page. I don't think there's a method of discovering capabilities though, although it would be nice if there was...

**Comment by fxprunayre** [comment]
I think we should avoid to put too much efforts in search API doc as this will change a lot with Elasticsearch move and some of the services may even be removed ...

**Comment by nmtoken** [comment]
So to summarise currently:

`{your server}/{your catalogue}/srv/eng/rdf.metadata.get?uuid={some_uuid}` 

gets a RDF record and 

`{your server}/{your catalogue}/srv/eng/rdf.search?` 

gets a dcat:Catalog RDF response describing all records in the catalogue, but there is no link between the dcat:dataset rdf:resource URL and the RDF record URL, ~ there's no link with form `{your server}/{your catalogue}/srv/eng/rdf.metadata.get?uuid={some_uuid}`, so even if we said the endpoint was `{your server}/{your catalogue}/srv/eng/rdf` something wouldn't be as expected.

Possibly my starting point should be the, also undocumented, OpenSearch resource?

`{your server}/{your catalogue}/srv/eng/portal.opensearch`  

which gives me inter al.

`<Url type="application/rdf+xml" template="{your server}/{your catalogue}/srv/eng/rdf.search?any={searchTerms}&hitsPerPage={count?}&bbox={geo:box?}&geometry={geo:geometry?}&name={geo:locationString?}"/>`

I'm not sure what effort should be put into documentation; some documentation would be good to describe what's currently available, and even a note to say what is likely to get replaced.

**Comment by fxprunayre** [comment]
https://trac.osgeo.org/geonetwork/wiki/proposals/DCATandRDFServices may help but is probably not completely up to date.

**Comment by archaeogeek** [comment]
I'm definitely in favour of some documentation on these blank pages- even if it's just the very basics  outlined above. Something is better than nothing, and it's not a lot of effort. I'm happy to add the basics, if others can then add to it as they explore further. @nmtoken would you be able to contribute?

@fxprunayre Also definite +1 for a note on which endpoints are likely to be deprecated as I'm sure I'm not the only one who uses various endpoints for business-critical functions and would be in a lot of trouble if they were dropped!

**Comment by nmtoken** [comment]
@archaeogeek I'll contribute if I'm able.

**Comment by archaeogeek** [comment]
@nmtoken and @fxprunayre I've submitted this PR https://github.com/geonetwork/doc/pull/70 to get a basic page started. Any contributions gratefully accepted!

**Comment by pvgenuchten** [comment]
slightly related here may be the future [ogc-api-records](https://github.com/opengeospatial/CAT4.0) endpoint, we have not yet considered how to adopt it, it will be an open api endpoint returning records (in various encodings i'd imagine).
I hope we can consider this endpoint in the upcoming elastic refactor

**Comment by archaeogeek** [comment]
Closing as https://github.com/geonetwork/doc/commit/cd5202c9d90fc4ba36d183e27b40365218673103 provides basics, anything additional can be added as a new issue
