### ISSUE TITLE
Style guide required

### ISSUE THREAD

**Issue by archaeogeek** [geonetwork/doc#53]
To ensure the documentation is consistent, we need a style guide. For example, how do we refer to the Catalog(ue)? Is it a catalog(ue) or a portal? What spelling do we use for the english version? I will start one in the wiki.

**Comment by fxprunayre** [comment]
I would add it to https://geonetwork-opensource.org/manuals/3.8.x/en/contributing/writing-documentation.html instead of the wiki.

**Comment by archaeogeek** [comment]
Fixed by https://github.com/geonetwork/doc/pull/84/commits/9b525d165b4c94bdf9f7071b67bb969ff2bf4859
