### ISSUE TITLE
Review workflow documentation

### ISSUE THREAD

**Issue by archaeogeek** [geonetwork/doc#65]
This page is blank: https://geonetwork-opensource.org/manuals/trunk/en/user-guide/workflow/versioning.html but the whole Workflow section at https://geonetwork-opensource.org/manuals/trunk/en/user-guide/workflow/index.html probably needs updating

**Comment by archaeogeek** [comment]
See also https://github.com/geonetwork/core-geonetwork/pull/3592

**Comment by archaeogeek** [comment]
@fxprunayre is versioning deprecated in 4.0.x onwards? (The code seems to suggest it is)

**Comment by archaeogeek** [comment]
See also https://github.com/geonetwork/doc/issues/138

**Comment by fxprunayre** [comment]
When we speak about versioning there is various topics. Now 3.12 or 4.x are mainly relying on database status when history is enabled from the settings (http://localhost:8080/srv/eng/admin.console?debug#/dashboard/versioning).

But we still have some SVN support (probably unused?) but still partially working - yesterday testing https://github.com/geonetwork/core-geonetwork/pull/7017 the subversion repository is still created but the Jeeves API looks broken - so probably something to cleanup.

**Comment by archaeogeek** [comment]
Indeed- this is specifically checking SVN rather than the newer workflow history I think.  In 3.10.x there is a blue javascript message present in admin console -> statistics and status -> versioning when SVN **is not** enabled (though I didn't check what happens when I enable it because that particular system is live) but in 4.2.x the message seems to be hidden when SVN **is** enabled but no events seem to be recorded.

I'm in favour of marking SVN support as deprecated and focusing more on Workflow- what do you think?

**Comment by fxprunayre** [comment]
I was also discussing yesterday with @josegar74 and @juanluisrp to drop SVN specific code.

**Comment by archaeogeek** [comment]
SVN section marked as deprecated in https://github.com/geonetwork/doc/commit/7fea1e402a5ccccc6c932c611fc47f3c740f3929

**Comment by archaeogeek** [comment]
Addressed in https://github.com/geonetwork/doc/pull/238
