### ISSUE TITLE
Change log review: (3.6.0): Map improvements

### ISSUE THREAD

**Issue by archaeogeek** [geonetwork/doc#66]
Projection switcher changes need adding to https://geonetwork-opensource.org/manuals/trunk/en/administrator-guide/configuring-the-catalog/system-configuration.html. Is there even a section in the help guide for the map?

**Comment by pvgenuchten** [comment]
@archaeogeek i added a bit here https://geonetwork-opensource.org/manuals/trunk/en/administrator-guide/configuring-the-catalog/user-interface-configuration.html, other suggestion?

**Comment by archaeogeek** [comment]
Looks good, happy to close this one
