### ISSUE TITLE
suggestions is only developer oriented

### ISSUE THREAD

**Issue by pvgenuchten** [geonetwork/doc#76]
the section should also be described from a user perspective

https://geonetwork-opensource.org/manuals/trunk/en/user-guide/workflow/suggestion.html

**Comment by archaeogeek** [comment]
Does it also need to be enhanced with (eg) https://github.com/geonetwork/core-geonetwork/pull/3864?

**Comment by archaeogeek** [comment]
I'm closing this because I think the current documentation at https://geonetwork-opensource.org/manuals/trunk/en/user-guide/workflow/suggestion.html is as user-oriented as it can be, given that the actual process of adding a suggestion must be done by a developer anyhow.
